import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        background: '#f9f9ff',
        surface: '#f9f9ff',
        'surface-dim': '#d0daf2',
        'surface-bright': '#f9f9ff',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f0f3ff',
        'surface-container': '#e8eeff',
        'surface-container-high': '#dfe8ff',
        'surface-container-highest': '#d9e3fb',
        'on-surface': '#111c2d',
        'on-surface-variant': '#424654',
        'inverse-surface': '#273143',
        'inverse-on-surface': '#ecf0ff',
        outline: '#737786',
        'outline-variant': '#c2c6d7',
        'surface-tint': '#0056d0',
        primary: '#0055ce',
        'on-primary': '#ffffff',
        'primary-container': '#2f6fed',
        'on-primary-container': '#ffffff',
        'inverse-primary': '#b1c5ff',
        secondary: '#565e71',
        'on-secondary': '#ffffff',
        'secondary-container': '#dbe2f9',
        'on-secondary-container': '#5c6477',
        tertiary: '#006c3c',
        'on-tertiary': '#ffffff',
        'tertiary-container': '#00884c',
        'on-tertiary-container': '#ffffff',
        error: '#ba1a1a',
        'on-error': '#ffffff',
        'error-container': '#ffdad6',
        'on-error-container': '#93000a',
        'primary-fixed': '#dae2ff',
        'primary-fixed-dim': '#b1c5ff',
        'on-primary-fixed': '#001847',
        'on-primary-fixed-variant': '#0040a0',
        'secondary-fixed': '#dbe2f9',
        'secondary-fixed-dim': '#bfc6dc',
        'on-secondary-fixed': '#141b2c',
        'on-secondary-fixed-variant': '#3f4759',
        'tertiary-fixed': '#70fda7',
        'tertiary-fixed-dim': '#51df8e',
        'on-tertiary-fixed': '#00210e',
        'on-tertiary-fixed-variant': '#00522c',
      },
      fontFamily: {
        sans: ['Inter', 'system-ui', '-apple-system', 'BlinkMacSystemFont', 'sans-serif'],
      },
      borderRadius: {
        DEFAULT: '0.5rem',
        sm: '0.25rem',
        md: '0.75rem',
        lg: '1rem',
        xl: '1.25rem',
        '2xl': '1.5rem',
        full: '9999px',
      }
    },
  },
  plugins: [],
};
export default config;
