import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: 'class',
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        background: '#F5F7FA',
        surface: '#FFFFFF',
        'surface-dim': '#EFF4FF',
        'surface-bright': '#FFFFFF',
        'surface-container-lowest': '#FFFFFF',
        'surface-container-low': '#F5F7FA',
        'surface-container': '#EFF4FF',
        'surface-container-high': '#E4E7EC',
        'surface-container-highest': '#D0D5DD',
        'on-surface': '#101828',
        'on-surface-variant': '#667085',
        'inverse-surface': '#101828',
        'inverse-on-surface': '#F5F7FA',
        outline: '#E4E7EC',
        'outline-variant': '#D0D5DD',
        'surface-tint': '#2F6FED',
        primary: {
          DEFAULT: '#2F6FED',
          hover: '#2458C7',
          light: '#EFF4FF',
          dark: '#1D4ED8',
        },
        'on-primary': '#FFFFFF',
        'primary-container': '#2F6FED',
        'on-primary-container': '#FFFFFF',
        'inverse-primary': '#B2CCFF',
        secondary: '#667085',
        'on-secondary': '#FFFFFF',
        'secondary-container': '#F2F4F7',
        'on-secondary-container': '#344054',
        success: {
          DEFAULT: '#12B76A',
          light: '#ECFDF3',
          dark: '#027A48',
        },
        warning: {
          DEFAULT: '#F79009',
          light: '#FFFAEB',
          dark: '#B54708',
        },
        error: {
          DEFAULT: '#F04438',
          light: '#FEF3F2',
          dark: '#B42318',
        },
        leak: {
          DEFAULT: '#F04438',
          light: '#FEF3F2',
          dark: '#B42318',
        },
        brand: {
          bg: '#F5F7FA',
          surface: '#FFFFFF',
          border: '#E4E7EC',
          blue: '#2F6FED',
          'blue-pill': '#EFF4FF',
          text: '#101828',
          muted: '#667085',
          green: '#12B76A',
          'green-pill': '#ECFDF3',
          amber: '#F79009',
          'amber-pill': '#FFFAEB',
          red: '#F04438',
          'red-pill': '#FEF3F2',
        },
      },
      fontFamily: {
        sans: ['Inter', 'system-ui', '-apple-system', 'BlinkMacSystemFont', 'sans-serif'],
      },
      borderRadius: {
        DEFAULT: '0.5rem',
        sm: '0.25rem',
        md: '0.75rem',
        lg: '1rem',
        xl: '1.25rem',
        '2xl': '1.5rem',
        full: '9999px',
      }
    },
  },
  plugins: [],
};
export default config;
